require_relative 'main.rb'

task :word do
  Text2Voice.synth(
    text: 'hola', 
    audio_path: 'public/audio/es/hola.mp3',
    client: Text2Voice.client,
    voiceid: 'Conchita'  # Spanish voice
  )
end

task :txt2voice do
  Text2Voice.run(
    data_path: 'public/src/data_spanish_verbs.json', 
    output_path: 'public/audio',
    voiceid: ['Conchita','Joanna'],  # Spanish and English voices
    override: true
  )
end